/*
 * API ServiceOrder
 * Request the instantiation of a service  A Service Order is a type of order which can be used to describe a group of operations on service – one service order item per service. An action at the level of the service order item describe the operation to be done on a service (add, terminate for example). The service order is triggered from the BSS system in charge of the product order management to ONAP that will manage the service fulfillment.  List of available subscription for serviceOrdering notifications, see /hub resources for more information:  - ServiceOrderCreationNotification - ServiceOrderStateChangeNotification - ServiceOrderItemStateChangeNotification  
 *
 * OpenAPI spec version: 4.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Value is a descriptive structure for service characteristic
 */
@Schema(description = "Value is a descriptive structure for service characteristic")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-22T18:40:19.698152-04:00[America/Toronto]")
public class Value {
  @SerializedName("serviceCharacteristicValue")
  private String serviceCharacteristicValue = null;

  public Value serviceCharacteristicValue(String serviceCharacteristicValue) {
    this.serviceCharacteristicValue = serviceCharacteristicValue;
    return this;
  }

   /**
   * Value of the characteristic.
   * @return serviceCharacteristicValue
  **/
  @Schema(description = "Value of the characteristic.")
  public String getServiceCharacteristicValue() {
    return serviceCharacteristicValue;
  }

  public void setServiceCharacteristicValue(String serviceCharacteristicValue) {
    this.serviceCharacteristicValue = serviceCharacteristicValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Value value = (Value) o;
    return Objects.equals(this.serviceCharacteristicValue, value.serviceCharacteristicValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceCharacteristicValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Value {\n");
    
    sb.append("    serviceCharacteristicValue: ").append(toIndentedString(serviceCharacteristicValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
